<a href="https://colab.research.google.com/github/Fahad035/Fahad035/blob/main/problem3(161023748035).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mpd

In [ ]:
dataset = pd.read_csv('sample_data.csv')
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
dataset.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
dataset.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [ ]:
dataset = dataset.drop_duplicates()
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
dataset.isnull()

   Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [ ]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
x = dataset[['Country','Age','Salary']].values
y = dataset['Purchased'].values

print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

print(x_train)

[[1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 50.0 83000.0]]

In [ ]:
print(x_test)

[[0.0 1.0 0.0 40.0 nan]
 [0.0 0.0 1.0 27.0 48000.0]]

In [ ]:
print(y_train)

['Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No']

In [ ]:
print(y_test)

['Yes' 'Yes']

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,4:]=sc.fit_transform(x_train[:,4:])

In [ ]:
print(x_train)

[[1.0 0.0 0.0 35.0 -0.7213204519277457]
 [1.0 0.0 0.0 44.0 0.5817100418772143]
 [1.0 0.0 0.0 48.0 1.2332252887796944]
 [0.0 1.0 0.0 30.0 -1.093614878729163]
 [0.0 0.0 1.0 38.0 -0.4420996318266829]
 [0.0 0.0 1.0 nan -1.2797620921298716]
 [1.0 0.0 0.0 37.0 0.11634200837544287]
 [0.0 1.0 0.0 50.0 1.6055197155811116]]

In [ ]:
print(x_test)

[[0.0 1.0 0.0 40.0 nan]
 [0.0 0.0 1.0 27.0 48000.0]]

In [ ]:
x_test[:,4:]=sc.transform(x_test[:,4:])
print(x_test)

[[0.0 1.0 0.0 40.0 nan]
 [0.0 0.0 1.0 27.0 -1.6520565189312888]]